"""empty message

Revision ID: c4fbecc9caea
Revises: ec048f98c9ec
Create Date: 2024-05-13 22:07:53.610734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4fbecc9caea'
down_revision = 'ec048f98c9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memory256', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('memory512', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('memory1', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('memory1')
        batch_op.drop_column('memory512')
        batch_op.drop_column('memory256')

    # ### end Alembic commands ###
